#!/usr/bin/env node
'use strict'

import fs from 'node:fs'
import path from 'node:path'
import { execFileSync } from 'node:child_process'
import { fileURLToPath, pathToFileURL } from 'node:url'

/**
 * Regenerate the Field Notes feed files + sitemap +
 * per-issue OG/Twitter cards from the array in
 * `landing/src/data/fieldNotes.js`. By default writes all
 * of the following:
 *
 *   landing/public/rss.xml                              — full feed, RSS 2.0 XML
 *   landing/public/feed.txt                             — full feed, plain text
 *   landing/public/latest.xml                           — latest post only, RSS 2.0 XML
 *   landing/public/latest.txt                           — latest post only, plain text
 *   landing/public/sitemap.xml                          — sitemap protocol 0.9, every static
 *                                                       route + one <url> per post with
 *                                                       <lastmod> from pubDate
 *   landing/public/field-notes/<slug>/og.png            — per-issue OG card (1200×630)
 *   landing/public/field-notes/<slug>/twitter.png       — per-issue Twitter card (1200×675)
 *
 * The per-issue cards are generated by `scripts/build-issue-cards.mjs`,
 * invoked here as a subprocess so the feed script doesn't
 * pull the SVG / ImageMagick composition logic into its own
 * module tree. Both scripts share the `fieldNotes` data
 * source, so editing a post's title / issuePrefix / pubDate
 * / body and running `yarn feeds:build` refreshes every
 * public surface in one pass.
 *
 * The `latest.*` pair is the public link target for "ping me
 * when there's a new post" — feed readers and one-off
 * subscribers can poll a tiny file instead of re-parsing the
 * whole archive. The `rss.xml` / `feed.txt` pair stays the
 * full archive for readers that want the back catalog. The
 * sitemap is the discovery surface for Google Search Console
 * and the autodiscoverer crawled by `robots.txt`. The cards
 * are the social-platform preview surface (OG, Twitter,
 * LinkedIn, Slack) — see `landing/src/components/seo/SEO.jsx`
 * for the per-page meta tag wiring.
 *
 * All artifacts are committed; consumers don't have to ship
 * a build step. Run this script after adding or editing a
 * post and commit the result.
 *
 * After writing the feed files, the script fires a
 * `POST /api/newsletter/broadcast` against the running
 * server if `API_URL` and `NEWSLETTER_ADMIN_SECRET` are in
 * the environment. The server queues a broadcast to every
 * active subscriber who hasn't received the latest slug yet
 * (see `server/src/utils/newsletterBroadcast.js`). The
 * broadcast itself is async — the script returns as soon as
 * the server returns 202, and the server logs progress from
 * then on.
 *
 * Env loading is a tiny inline parser (KEY=value lines, no
 * quoting) so the script doesn't need dotenv as a transitive
 * dependency — the server already requires it, but it's not
 * hoisted to the root node_modules. `.env.<NODE_ENV>` is
 * loaded if it exists, but only for keys that aren't already
 * in `process.env` (shell-set vars win). When
 * `NODE_ENV === 'production'` it loads `.env.prod`;
 * otherwise `.env.dev`. Both files are gitignored.
 *
 * Usage:
 *   node scripts/build-rss.mjs                # write all feeds + cards + broadcast
 *   node scripts/build-rss.mjs --xml-only     # only the XML files (rss + latest + sitemap)
 *   node scripts/build-rss.mjs --txt-only     # only the TXT files (feed + latest)
 *   node scripts/build-rss.mjs --full-only    # skip the latest only
 *   node scripts/build-rss.mjs --latest-only  # skip the full files
 *   node scripts/build-rss.mjs --no-write     # skip file writes (feeds + cards + sitemap); broadcast only
 *   node scripts/build-rss.mjs --no-cards     # skip the per-issue OG/Twitter card regen (feeds + sitemap only)
 *   node scripts/build-rss.mjs --no-broadcast # skip the broadcast (build only)
 *   node scripts/build-rss.mjs --dry-run      # print everything to stdout
 *
 * `--no-write` and `--no-broadcast` are independent of the
 * format/variant flags and compose with them. They're how the
 * yarn aliases split the two concerns:
 *   - `feeds:build`         — pre-commit, write files only
 *   - `feeds:broadcast-dev` — dev send, broadcast only
 *   - `feeds:broadcast`     — prod send, broadcast only
 *
 * Format flags and variant flags compose: `--xml-only
 * --latest-only` writes only `latest.xml`. `--full-only
 * --xml-only` writes only `rss.xml`. The sitemap is its own
 * format (XML, but not a feed) — it ships with `--xml-only`
 * but not with `--txt-only`, and is unaffected by the
 * `--full-only` / `--latest-only` variant flags since it
 * always emits every static route plus every post.
 *
 * Why not a Vite plugin: the public folder is served as-is
 * (no transform), and a regen step at edit time is more
 * auditable than a side-effect at bundle time.
 *
 * The data module is intentionally self-contained (it does not
 * import from `landing/src/config.js`), so it loads cleanly in
 * raw Node without needing the Vite-specific `import.meta.env`
 * shim.
 */

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(__dirname, '..')

// ── arg parsing ──────────────────────────────────────────────────────────
const args = process.argv.slice(2)
const dryRun = args.includes('--dry-run')
const xmlOnly = args.includes('--xml-only')
const txtOnly = args.includes('--txt-only')
const fullOnly = args.includes('--full-only')
const latestOnly = args.includes('--latest-only')
const noWrite = args.includes('--no-write')
const noCards = args.includes('--no-cards')
const noBroadcast = args.includes('--no-broadcast')

// `--xml-only` and `--txt-only` are mutually exclusive; if
// neither is set we write both formats. The sitemap is
// sitemap-protocol XML — it rides on `--xml-only` rather
// than getting its own flag, because the only file that
// has no analogue in the other format is the sitemap and
// the natural group "stuff Vite serves at the site root"
// is XML-shaped.
const writeXml = !txtOnly
const writeTxt = !xmlOnly
const writeSitemap = !txtOnly

// `--full-only` and `--latest-only` are mutually exclusive; if
// neither is set we write both variants.
const writeFull = !latestOnly
const writeLatest = !fullOnly

// ── env loading ──────────────────────────────────────────────────────────
// Tiny inline .env parser. Reads KEY=value lines, ignores
// comments and blank lines, doesn't quote. Only sets a key if
// it's not already in process.env (shell wins). NODE_ENV
// picks which file to load: production -> .env.prod, anything
// else -> .env.dev.
const NODE_ENV = process.env.NODE_ENV || 'development'
const envFileName = NODE_ENV === 'production' ? '.env.prod' : '.env.dev'
const envFilePath = path.join(repoRoot, envFileName)

if (fs.existsSync(envFilePath)) {
  const content = fs.readFileSync(envFilePath, 'utf8')
  for (const rawLine of content.split('\n')) {
    const line = rawLine.trim()
    if (!line || line.startsWith('#')) continue
    const eq = line.indexOf('=')
    if (eq === -1) continue
    const key = line.slice(0, eq).trim()
    if (!key || key in process.env) continue
    process.env[key] = line.slice(eq + 1).trim()
  }
}

// ── dynamic import of the data module ────────────────────────────────────
// Both modules load cleanly in raw Node — they have no Vite-specific
// `import.meta.env` reads, so the regen script doesn't need the Vite
// shim. `BRAND_DOMAIN` is imported from `data/brand.js` (the single
// source of truth for brand strings); the field-notes module re-exports
// nothing we need beyond the builders and `getLatest`.
const fieldNotesPath = path.join(
  repoRoot,
  'landing/src/data/fieldNotes.js',
)
const brandPath = path.join(
  repoRoot,
  'landing/src/data/brand.js',
)
const { buildRss, buildFeedTxt, buildSitemap, getLatest } = await import(
  pathToFileURL(fieldNotesPath).href
)
const { BRAND_DOMAIN } = await import(pathToFileURL(brandPath).href)

// Latest post as a one-element array. `getLatest()` returns
// null if the data is empty; fall back to an empty array so
// the builders still emit a well-formed (but item-less) feed
// rather than throwing.
const latestNote = getLatest()
const latestNotes = latestNote ? [latestNote] : []

// ── build the (path, content) pairs we'll write ─────────────────────────
// Each pair is independent so --dry-run can print them all
// and any combination of format/variant flags just narrows
// the list.
const files = []

if (writeFull) {
  if (writeXml) files.push(['landing/public/rss.xml', buildRss()])
  if (writeTxt) files.push(['landing/public/feed.txt', buildFeedTxt()])
}
if (writeLatest) {
  if (writeXml) files.push(['landing/public/latest.xml', buildRss(latestNotes)])
  if (writeTxt) files.push(['landing/public/latest.txt', buildFeedTxt(latestNotes)])
}
// Sitemap is its own format — every static route plus every
// post, regardless of `--full-only` / `--latest-only`. The
// variant flags are a feeds concern; the sitemap is a
// discovery concern and is unaffected by them.
if (writeSitemap) files.push(['landing/public/sitemap.xml', buildSitemap()])

if (dryRun) {
  files.forEach(([rel, content], i) => {
    if (i > 0) process.stdout.write('\n')
    process.stdout.write(`── ${rel}\n`)
    process.stdout.write(content)
  })
  process.exit(0)
}

// ── write ────────────────────────────────────────────────────────────────
if (noWrite) {
  console.log('⊘ File writes skipped (--no-write)')
} else {
  for (const [rel, content] of files) {
    const outPath = path.resolve(repoRoot, rel)
    fs.writeFileSync(outPath, content, 'utf8')
    console.log(`✓ Wrote ${path.relative(repoRoot, outPath)}`)
  }
}

// ── per-issue OG / Twitter cards ─────────────────────────────────────
// Regenerate the per-issue Open Graph and Twitter cards
// from the same `fieldNotes` array the feeds are built
// from. They live next to each post's body assets at
// `landing/public/field-notes/<slug>/{og,twitter}.png` and
// are committed artifacts — same lifecycle as rss.xml /
// feed.txt. `scripts/build-issue-cards.mjs` is the
// dedicated entry point for a single-issue regen; here we
// invoke it as a subprocess so the feed script doesn't
// pull the puppeteer / headless-browser logic into its
// own module tree.
//
// Cards follow the same write gate as the feeds — they're
// committed artifacts that get refreshed by `yarn feeds:build`
// and are assumed fresh when `yarn feeds:broadcast-dev` /
// `yarn feeds:broadcast` fire against them (the broadcast
// scripts are pre-commit / post-deploy steps; running them
// without a prior `feeds:build` would mean stale artifacts,
// which is a workflow issue, not something the gate papers
// over).
//
// The `--dry-run` flag forwards to the cards script so a
// full preview prints every artifact that *would* be
// written without touching the filesystem.
if (noCards) {
  console.log('⊘ Per-issue cards skipped (--no-cards)')
} else if (!noWrite) {
  const cardsArgs = ['scripts/build-issue-cards.mjs']
  if (dryRun) cardsArgs.push('--dry-run')
  try {
    execFileSync('node', cardsArgs, { stdio: 'inherit' })
  } catch (err) {
    console.error(`error: build-issue-cards failed (exit ${err.status ?? '?'})`)
    process.exit(1)
  }
}

// ── broadcast ───────────────────────────────────────────────────────────
// Fires `POST /api/newsletter/broadcast` against the running
// server if the env has `API_URL` and `NEWSLETTER_ADMIN_SECRET`.
// Skipped silently otherwise (a quick local regen doesn't need
// to email every subscriber, and a CI without those vars just
// regenerates feeds without broadcasting).
//
// The broadcast is best-effort — failure logs a warning but
// doesn't fail the build. The feed files are already on disk;
// whether the email blast lands is a separate concern that
// the server's own run summary reports.
const apiUrl = process.env.API_URL
const adminSecret = process.env.NEWSLETTER_ADMIN_SECRET

if (noBroadcast) {
  console.log('⊘ Broadcast skipped (--no-broadcast)')
} else if (latestNote && apiUrl && adminSecret) {
  const url = `https://${BRAND_DOMAIN}/field-notes/${latestNote.slug}`
  const payload = {
    slug: latestNote.slug,
    issuePrefix: latestNote.issuePrefix,
    title: latestNote.title,
    description: latestNote.description,
    pubDate: latestNote.pubDate,
    url,
    ...(latestNote.author ? { author: latestNote.author } : {}),
  }
  try {
    const res = await fetch(`${apiUrl.replace(/\/$/, '')}/api/newsletter/broadcast`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-admin-secret': adminSecret,
      },
      body: JSON.stringify(payload),
    })
    if (res.ok) {
      console.log(`✓ Broadcast queued for ${latestNote.slug} (HTTP ${res.status})`)
    } else {
      let detail = ''
      try {
        detail = await res.text()
      } catch {
        // ignore — non-JSON body, status code is enough
      }
      console.warn(
        `⚠ Broadcast endpoint returned ${res.status}: ${detail || '(no body)'}`
      )
    }
  } catch (err) {
    console.warn(`⚠ Broadcast request failed: ${err.message}`)
  }
} else if (latestNote && (!apiUrl || !adminSecret)) {
  console.log(
    '⊘ Broadcast skipped (set API_URL + NEWSLETTER_ADMIN_SECRET to enable)'
  )
}